### ISSUE TITLE
Unable to Import / Separate .STP File

### ISSUE THREAD

**Issue by jborg-7** [maestrakos/warp#3]
I am having considerable trouble importing the model into SolidWorks 2018. It is a Premium license with FeatureWorks but the multi-bodies are not separating out like they should. 

Depending on the program you used to model this, is there any way you can upload an IGES file, a pack-n-go form of the model, or the raw assembly file?

Huge fan of the project, thank you for making this CC!
-Jared

**Comment by maestrakos** [comment]
Hi! Unfortunately I can't export the the 3D model as a raw assembly file or .iges. I tried using a website to convert the .step file to .iges and it worked, please give this a try: https://convert.emachineshop.com/

**Comment by alexandrospetkos** [comment]
Hi! Unfortunately I can't export the the 3D model to a raw assembly file or .iges. I tried using a website to convert the .step file to .iges and it worked, please give this a try: https://convert.emachineshop.com/
